apiVersion : apps/v1
kind: Deployment
metadata:
  name: "poccluster-9474"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "poccluster-9474"
  template:
    metadata:
      labels:
        app: "poccluster-9474"
    spec:
      containers:
        - name: "poccluster-9474"
          image: "aksdevsampleregistry.azurecr.io/poccluster"
          ports:
          - containerPort: 80