apiVersion: v1
kind: Service
metadata:
    name: "poccluster-9474"
    labels:
        app: "poccluster-9474"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "poccluster-9474"