on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aksdevsampleregistry.azurecr.io
        username: ${{ secrets.acr_aksdevsampleregistry_username }}
        password: ${{ secrets.acr_aksdevsampleregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/containers/powershell/.devcontainer" -f  "containers/powershell/.devcontainer/Dockerfile" -t aksdevsampleregistry.azurecr.io/poccluster:${{ github.sha }} --label dockerfile-path=containers/powershell/.devcontainer/Dockerfile
        docker push aksdevsampleregistry.azurecr.io/poccluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_poccluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep poc-clusterb5d9 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace poc-clusterb5d9`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: poc-clusterb5d9
        container-registry-url: aksdevsampleregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_aksdevsampleregistry_username }}
        container-registry-password: ${{ secrets.acr_aksdevsampleregistry_password }}
        secret-name: pocclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: poc-clusterb5d9
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          aksdevsampleregistry.azurecr.io/poccluster:${{ github.sha }}
        imagepullsecrets: |
          pocclusterdockerauth
