on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n AKSDevSampleRegistry -g AKSDevSampleRegistryb62e-rg --location "Canada Central" --sku Basic --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n AKSDevSampleRegistry --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n AKSDevSampleRegistry --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n AKSDevSampleRegistry --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: aksdevsampleregistry.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/containers/azure-static-web-apps/.devcontainer" -f  "containers/azure-static-web-apps/.devcontainer/Dockerfile" -t aksdevsampleregistry.azurecr.io/poccluster:${{ github.sha }} --label dockerfile-path=containers/azure-static-web-apps/.devcontainer/Dockerfile
        docker push aksdevsampleregistry.azurecr.io/poccluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_poccluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep poc-cluster94b6 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace poc-cluster94b6`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: poc-cluster94b6
        container-registry-url: aksdevsampleregistry.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: pocclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: poc-cluster94b6
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          aksdevsampleregistry.azurecr.io/poccluster:${{ github.sha }}
        imagepullsecrets: |
          pocclusterdockerauth   
